INSERT INTO authors(name_first, name_last)
VALUES
    ('Adam', 'Higginbotham'),
    ('Robert', 'Dugoni'),
    ('Christopher', 'Reich'),
    ('Hampton', 'Sides'),
    ('Stephen', 'King'),
    ('Erik', 'Blehm'),
    ('Adam', 'Markos'),
    ('Adam', 'Schiff'),
    ('Ann', 'Patchett'),
    ('Attica', 'Locke'),
    ('Beverly', 'Gage'),
    ('Bill', 'Browder'),
    ('Brad', 'Thor'),
    ('Brian', 'Stelter'),
    ('Bruce', 'Tate'),
    ('C.J.', 'Box'),
    ('Leonnig', 'Carol'),
    ('Philip', 'Rucker'),
    ('Daniel James', 'Brown'),
    ('Daniel', 'Silva'),
    ('David E.', 'Sanger'),
    ('David', 'Grann'),
    ('David', 'Zucker'),
    ('Jim', 'Abrahams'),
    ('Jerry', 'Zucker'),
    ('Deepti', 'Kappor'),
    ('Dennis', 'McDougal'),
    ('Eric', 'Foner'),
    ('Erik', 'Larson'),
    ('Eriq', 'La Salle'),
    ('Franklin', 'Foer'),
    ('Garrett M.', 'Graff'),
    ('Jacqueline', 'Winspear'),
    ('James B.', 'Stewart'),
    ('Rachel', 'Abrams'),
    ('James', 'Scott'),
    ('John', 'Galligan'),
    ('Jon', 'Meacham'),
    ('Jonathan', 'Karl'),
    ('Joseph', 'Pfeifer'),
    ('Kathryn', 'Miles'),
    ('Kim Stanley', 'Robinson'),
    ('Lawrence', 'Wright'),
    ('Len', 'Deighton'),
    ('McKay', 'Coppins'),
    ('Michael', 'Connelly'),
    ('Ottessa', 'Moshfegh'),
    ('Patrick', 'O''Brian'),
    ('Ruth', 'Ware'),
    ('S.A.', 'Cosby'),
    ('Shelly', 'King'),
    ('Steve', 'Hamilton'),
    ('Stuart', 'Stevens'),
    ('T.J.', 'Newman'),
    ('Tim', 'Miller'),
    ('Walter', 'Isaacson');
